[secrets]
GOOGLE_API_KEY = "AIzaSyBdZC9KKqYzsmgIyze30E_zQ3vhvyE2jmQ"
API_BASE_URL = "https://vs15-internet-banking-back.onrender.com"
DB_HOST = "dpg-cusuqkbtq21c73b9u390-a.oregon-postgres.render.com"
DB_NAME = "tf_bank"
DB_USER = "user"
DB_PASSWORD = "RrPtpR61rrqeTx35iii9otnYxJoOdIU4"
